export const crawlDataExample1 = {
    explored: {
        'https://www.github.com/': true,
        'https://www.github.blog/': true,
    },
    addedNodes: {
        'https://www.github.com/': true,
        'https://www.github.com/signup?ref_cta=Sign%20up,ref_loc=header%20logged%20out,ref_page=/,source=header-home': true,
        'https://www.github.com/features/actions': true,
        'https://www.github.com/features/packages': true,
        'https://www.github.com/features/security': true,
        'https://www.github.com/features/codespaces': true,
        'https://www.github.com/features/copilot': true,
        'https://www.github.com/features/code-review': true,
        'https://www.github.com/features/issues': true,
        'https://www.github.com/features/discussions': true,
        'https://www.github.com/features': true,
        'https://www.docs.github.com/': true,
        'https://www.skills.github.com/': true,
        'https://www.github.com/enterprise': true,
        'https://www.github.com/team': true,
        'https://www.github.com/enterprise/startups': true,
        'https://www.education.github.com/': true,
        'https://www.github.com/solutions/ci-cd': true,
        'https://www.resources.github.com/devops': true,
        'https://www.resources.github.com/devops/fundamentals/devsecops': true,
        'https://www.github.com/customer-stories': true,
        'https://www.resources.github.com/': true,
        'https://www.partner.github.com/': true,
        'https://www.github.com/sponsors': true,
        'https://www.github.com/readme': true,
        'https://www.github.com/topics': true,
        'https://www.github.com/trending': true,
        'https://www.github.com/collections': true,
        'https://www.github.com/pricing': true,
        'https://www.docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax': true,
        'https://www.github.com/login': true,
        'https://www.github.com/features/preview/copilot-x': true,
        'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=Home%20campaign%20hero,ref_page=/': true,
        'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=homepage%20sticky%20nav,ref_page=/': true,
        'https://www.github.com/join?ref_cta=Sign%20up%20for%20GitHub,ref_loc=homepage%20sticky%20nav,ref_page=/,source=homepage-sticky-nav': true,
        'https://www.github.com/mobile': true,
        'https://www.github.com/kazupon': true,
        'https://www.github.com/dayhaysoos': true,
        'https://www.github.com/homebrew': true,
        'https://www.github.com/eslint': true,
        'https://www.github.com/commandpost': true,
        'https://www.github.com/sindresorhus': true,
        'https://www.github.com/directus': true,
        'https://www.github.com/yyx990803': true,
        'https://www.github.com/prophen': true,
        'https://www.github.com/features/security/code': true,
        'https://www.github.com/features/security/software-supply-chain': true,
        'https://www.resources.github.com/security/sast': true,
        'https://www.github.com/signup?ref_cta=Sign%20up%20for%20GitHub,ref_loc=Home%20campaign%20footer,ref_page=/': true,
        'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=Home%20campaign%20footer,ref_page=/': true,
        'https://www.resources.github.com/newsletter': true,
        'https://www.github.com/security': true,
        'https://www.github.com/customer-stories?type=enterprise': true,
        'https://www.github.com/github/roadmap': true,
        'https://www.resources.github.com/devops/tools/compare': true,
        'https://www.docs.github.com/get-started/exploring-integrations/about-building-integrations': true,
        'https://www.electronjs.org/': true,
        'https://www.desktop.github.com/': true,
        'https://www.github.community/': true,
        'https://www.services.github.com/': true,
        'https://www.github.com/premium-support': true,
        'https://www.githubstatus.com/': true,
        'https://www.support.github.com/?tags=dotcom-footer': true,
        'https://www.github.com/about': true,
        'https://www.github.com/about/careers': true,
        'https://www.github.com/about/press': true,
        'https://www.github.com/about/diversity': true,
        'https://www.socialimpact.github.com/': true,
        'https://www.shop.github.com/': true,
        'https://www.twitter.com/github': true,
        'https://www.facebook.com/github': true,
        'https://www.linkedin.com/company/github': true,
        'https://www.youtube.com/github': true,
        'https://www.twitch.tv/github': true,
        'https://www.tiktok.com/@github': true,
        'https://www.github.com/github': true,
        'https://www.docs.github.com/site-policy/github-terms/github-terms-of-service': true,
        'https://www.docs.github.com/site-policy/privacy-policies/github-privacy-statement': true,
        'https://www.github.com/github/site-policy/pull/582': true,
        'https://www.github.com/sitemap': true,
        'https://www.github.com/git-guides': true,
        'https://www.github.blog/': true,
        'https://www.github.blog/category/engineering': true,
        'https://www.github.blog/category/product': true,
        'https://www.github.blog/category/security': true,
        'https://www.github.blog/category/open-source': true,
        'https://www.github.blog/category/enterprise': true,
        'https://www.github.blog/changelog': true,
        'https://www.github.blog/category/community': true,
        'https://www.github.blog/category/education': true,
        'https://www.github.blog/category/company': true,
        'https://www.github.blog/category/policy': true,
        'https://www.github.com/enterprise/trial?ref_cta=free%20trial,ref_loc=banner,ref_page=blog': true,
        'https://www.github.com/enterprise/contact?ref_cta=contact%20sales,ref_loc=banner,ref_page=blog': true,
        'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations': true,
        'https://www.github.blog/author/nyczain': true,
        'https://www.github.blog/author/courtneycl': true,
        'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program': true,
        'https://www.github.blog/author/thejillboss': true,
        'https://www.github.blog/2023-08-09-github-availability-report-july-2023': true,
        'https://www.github.blog/author/jakuboleksy': true,
        'https://www.github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure': true,
        'https://www.github.blog/author/jarlob': true,
        'https://www.github.blog/author/kevinbackhouse': true,
        'https://www.github.blog/2023-08-08-a-guide-to-designing-and-shipping-ai-developer-tools': true,
        'https://www.github.blog/author/nicchoi29': true,
        'https://www.github.blog/2023-08-04-a-checklist-and-guide-to-get-your-repository-collaboration-ready': true,
        'https://www.github.blog/author/peckjon': true,
        'https://www.github.blog/2023-08-03-introducing-code-referencing-for-github-copilot': true,
        'https://www.github.blog/author/ryanjsalva': true,
        'https://www.github.blog/2023-08-02-best-practices-for-organizations-and-teams-using-github-enterprise-cloud': true,
        'https://www.github.blog/author/davelosert': true,
        'https://www.github.blog/author/elizabethbarrord': true,
        'https://www.github.blog/2023-08-02-how-we-build-containerized-services-at-github-using-github': true,
        'https://www.github.blog/author/mvkaran': true,
        'https://www.github.blog/author/kagamicat': true,
        'https://www.github.blog/2023-07-28-smarter-more-efficient-coding-github-copilot-goes-beyond-codex-with-improved-ai-model': true,
        'https://www.github.blog/author/shuyinzjk': true,
        'https://www.github.blog/changelog/2023-08-14-new-dataflow-api-for-writing-custom-codeql-queries': true,
        'https://www.github.blog/changelog/2023-08-11-github-copilot-august-10th-update': true,
        'https://www.github.blog/changelog/2023-08-11-secret-scanning-supports-on-demand-token-validity-checks': true,
        'https://www.github.blog/changelog/2023-08-10-ignore-or-unignore-updates-for-grouped-dependabot-pull-requests': true,
        'https://www.github.blog/2023-07-27-scaling-merge-ort-across-github': true,
        'https://www.github.blog/author/vtbassmatt': true,
        'https://www.github.blog/2023-07-25-game-bytes-july-2023': true,
        'https://www.github.blog/author/leereilly': true,
        'https://www.github.blog/2023-07-13-release-radar-spring-23': true,
        'https://www.github.blog/author/mishmanners': true,
        'https://www.github.blog/2023-07-13-decoding-conventions': true,
        'https://www.github.blog/author/martinwoodward': true,
        'https://www.github.blog/author/nerdneha': true,
        'https://www.github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps': true,
        'https://www.github.blog/author/bdougie': true,
        'https://www.github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13': true,
        'https://www.github.blog/author/lauraleap': true,
        'https://www.github.blog/author/hpsin': true,
        'https://www.github.blog/2023-06-20-how-to-write-better-prompts-for-github-copilot': true,
        'https://www.github.blog/author/blackgirlbytes': true,
        'https://www.github.blog/2022-09-07-research-quantifying-github-copilots-impact-on-developer-productivity-and-happiness': true,
        'https://www.github.blog/author/ikaliam': true,
        'https://www.github.blog/2023-07-25-how-to-responsibly-adopt-github-copilot-with-the-github-copilot-trust-center': true,
        'https://www.github.blog/author/shellsmck': true,
        'https://www.github.blog/2023-07-24-github-repository-rules-are-now-generally-available': true,
        'https://www.github.blog/author/patrickknight': true,
        'https://www.github.blog/2023-07-20-github-copilot-chat-beta-now-available-for-every-organization': true,
        'https://www.github.blog/author/mariorod': true,
        'https://www.github.blog/2023-07-28-closing-vulnerabilities-in-decidim-a-ruby-based-citizen-participation-platform': true,
        'https://www.github.blog/author/stockli': true,
        'https://www.github.blog/2023-07-18-security-alert-social-engineering-campaign-targets-technology-industry-employees': true,
        'https://www.github.blog/author/alexiswales': true,
        'https://www.github.blog/2023-07-12-introducing-passwordless-authentication-on-github-com': true,
        'https://www.github.blog/2023-07-26-how-to-get-ai-regulation-right-for-open-source': true,
        'https://www.github.blog/author/pcihon': true,
        'https://www.github.blog/2023-07-05-introduction-to-selinux': true,
        'https://www.github.blog/author/kwstubbs': true,
        'https://www.github.blog/2023-05-12-how-i-used-github-copilot-to-build-a-browser-extension': true,
        'https://www.github.blog/2023-05-05-building-a-more-inclusive-github-global-campus': true,
        'https://www.github.blog/author/arelia': true,
        'https://www.github.blog/2023-07-12-no-cyber-resilience-without-open-source-sustainability': true,
        'https://www.github.blog/author/mlinksva': true,
        'https://www.github.blog/2023-06-19-developers-need-the-right-to-challenge-junk-patents': true,
        'https://www.github.blog/2023-07-19-exploring-developer-happiness-inclusion-and-productivity-at-githubs-design-conference': true,
        'https://www.github.blog/author/amandaswan': true,
        'https://www.github.blog/2023-07-17-prompt-engineering-guide-generative-ai-llms': true,
        'https://www.github.blog/author/wunderalbert': true,
        'https://www.github.blog/author/jnbrymn': true,
        'https://www.github.blog/2023-07-12-github-merge-queue-is-generally-available': true,
        'https://www.github.blog/author/aspeckofdustin': true,
        'https://www.github.com/site/privacy': true,
        'https://www.developer.github.com/': true,
        'https://www.atom.io/': true,
        'https://www.support.github.com/': true,
        'https://www.docs.github.com/en/github/site-policy/github-terms-of-service': true,
        'https://www.docs.github.com/en/github/site-policy/github-privacy-statement': true,
    },
    groups: [
        'www.docs.github.com',
        'www.skills.github.com',
        'www.github.blog',
        'www.education.github.com',
        'www.resources.github.com',
        'www.partner.github.com',
        'www.electronjs.org',
        'www.desktop.github.com',
        'www.github.community',
        'www.services.github.com',
        'www.githubstatus.com',
        'www.support.github.com',
        'www.socialimpact.github.com',
        'www.shop.github.com',
        'www.twitter.com',
        'www.facebook.com',
        'www.linkedin.com',
        'www.youtube.com',
        'www.twitch.tv',
        'www.tiktok.com',
        'www.github.com',
        'www.developer.github.com',
        'www.atom.io',
    ],
};

export const graphDataExample1 = {
    nodes: [
        { id: 'https://www.github.com/', group: 1, distanceGroup: 1, explored: true },
        {
            id: 'https://www.github.com/signup?ref_cta=Sign%20up,ref_loc=header%20logged%20out,ref_page=/,source=header-home',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/actions',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/packages',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/security',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/codespaces',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/copilot',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/code-review',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/issues',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/discussions',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.docs.github.com/',
            group: 2,
            distanceGroup: 3,
            explored: false,
        },
        {
            id: 'https://www.skills.github.com/',
            group: 3,
            distanceGroup: 4,
            explored: false,
        },
        { id: 'https://www.github.blog/', group: 4, distanceGroup: 5, explored: true },
        {
            id: 'https://www.github.com/enterprise',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/team',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/enterprise/startups',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.education.github.com/',
            group: 5,
            distanceGroup: 6,
            explored: false,
        },
        {
            id: 'https://www.github.com/solutions/ci-cd',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.resources.github.com/devops',
            group: 6,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://www.resources.github.com/devops/fundamentals/devsecops',
            group: 4,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://www.github.com/customer-stories',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.resources.github.com/',
            group: 4,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://www.partner.github.com/',
            group: 7,
            distanceGroup: 8,
            explored: false,
        },
        {
            id: 'https://www.github.com/sponsors',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/readme',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/topics',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/trending',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/collections',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/pricing',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            group: 0,
            distanceGroup: 0,
            explored: false,
        },
        {
            id: 'https://www.github.com/login',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/preview/copilot-x',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=Home%20campaign%20hero,ref_page=/',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=homepage%20sticky%20nav,ref_page=/',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/join?ref_cta=Sign%20up%20for%20GitHub,ref_loc=homepage%20sticky%20nav,ref_page=/,source=homepage-sticky-nav',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/mobile',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/kazupon',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/dayhaysoos',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/homebrew',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/eslint',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/commandpost',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/sindresorhus',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/directus',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/yyx990803',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/prophen',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/security/code',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/security/software-supply-chain',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.resources.github.com/security/sast',
            group: 4,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://www.github.com/signup?ref_cta=Sign%20up%20for%20GitHub,ref_loc=Home%20campaign%20footer,ref_page=/',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=Home%20campaign%20footer,ref_page=/',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.resources.github.com/newsletter',
            group: 4,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://www.github.com/security',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/customer-stories?type=enterprise',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/github/roadmap',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.resources.github.com/devops/tools/compare',
            group: 4,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://www.docs.github.com/get-started/exploring-integrations/about-building-integrations',
            group: 0,
            distanceGroup: 0,
            explored: false,
        },
        {
            id: 'https://www.electronjs.org/',
            group: 8,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.desktop.github.com/',
            group: 9,
            distanceGroup: 10,
            explored: false,
        },
        {
            id: 'https://www.github.community/',
            group: 10,
            distanceGroup: 11,
            explored: false,
        },
        {
            id: 'https://www.services.github.com/',
            group: 11,
            distanceGroup: 12,
            explored: false,
        },
        {
            id: 'https://www.github.com/premium-support',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.githubstatus.com/',
            group: 12,
            distanceGroup: 13,
            explored: false,
        },
        {
            id: 'https://www.support.github.com/?tags=dotcom-footer',
            group: 13,
            distanceGroup: 14,
            explored: true,
        },
        {
            id: 'https://www.github.com/about',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/about/careers',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/about/press',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/about/diversity',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.socialimpact.github.com/',
            group: 14,
            distanceGroup: 15,
            explored: false,
        },
        {
            id: 'https://www.shop.github.com/',
            group: 15,
            distanceGroup: 16,
            explored: false,
        },
        {
            id: 'https://www.twitter.com/github',
            group: 16,
            distanceGroup: 17,
            explored: false,
        },
        {
            id: 'https://www.facebook.com/github',
            group: 17,
            distanceGroup: 18,
            explored: false,
        },
        {
            id: 'https://www.linkedin.com/company/github',
            group: 18,
            distanceGroup: 19,
            explored: false,
        },
        {
            id: 'https://www.youtube.com/github',
            group: 19,
            distanceGroup: 20,
            explored: false,
        },
        {
            id: 'https://www.twitch.tv/github',
            group: 20,
            distanceGroup: 21,
            explored: false,
        },
        {
            id: 'https://www.tiktok.com/@github',
            group: 21,
            distanceGroup: 22,
            explored: false,
        },
        {
            id: 'https://www.github.com/github',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.docs.github.com/site-policy/github-terms/github-terms-of-service',
            group: 0,
            distanceGroup: 0,
            explored: false,
        },
        {
            id: 'https://www.docs.github.com/site-policy/privacy-policies/github-privacy-statement',
            group: 0,
            distanceGroup: 0,
            explored: false,
        },
        {
            id: 'https://www.github.com/github/site-policy/pull/582',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/sitemap',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/git-guides',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/engineering',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/product',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/security',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/open-source',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/enterprise',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/changelog',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/community',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/education',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/company',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/category/policy',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/enterprise/trial?ref_cta=free%20trial,ref_loc=banner,ref_page=blog',
            group: 25,
            distanceGroup: 23,
            explored: false,
        },
        {
            id: 'https://www.github.com/enterprise/contact?ref_cta=contact%20sales,ref_loc=banner,ref_page=blog',
            group: 20,
            distanceGroup: 0,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/nyczain',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/courtneycl',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/thejillboss',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-09-github-availability-report-july-2023',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/jakuboleksy',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/jarlob',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/kevinbackhouse',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-08-a-guide-to-designing-and-shipping-ai-developer-tools',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/nicchoi29',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-04-a-checklist-and-guide-to-get-your-repository-collaboration-ready',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/peckjon',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-03-introducing-code-referencing-for-github-copilot',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/ryanjsalva',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-02-best-practices-for-organizations-and-teams-using-github-enterprise-cloud',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/davelosert',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/elizabethbarrord',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-08-02-how-we-build-containerized-services-at-github-using-github',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/mvkaran',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/kagamicat',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-28-smarter-more-efficient-coding-github-copilot-goes-beyond-codex-with-improved-ai-model',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/shuyinzjk',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/changelog/2023-08-14-new-dataflow-api-for-writing-custom-codeql-queries',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/changelog/2023-08-11-github-copilot-august-10th-update',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/changelog/2023-08-11-secret-scanning-supports-on-demand-token-validity-checks',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/changelog/2023-08-10-ignore-or-unignore-updates-for-grouped-dependabot-pull-requests',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-27-scaling-merge-ort-across-github',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/vtbassmatt',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-25-game-bytes-july-2023',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/leereilly',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-13-release-radar-spring-23',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/mishmanners',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-13-decoding-conventions',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/martinwoodward',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/nerdneha',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/bdougie',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/lauraleap',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/hpsin',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-06-20-how-to-write-better-prompts-for-github-copilot',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/blackgirlbytes',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2022-09-07-research-quantifying-github-copilots-impact-on-developer-productivity-and-happiness',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/ikaliam',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-25-how-to-responsibly-adopt-github-copilot-with-the-github-copilot-trust-center',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/shellsmck',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-24-github-repository-rules-are-now-generally-available',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/patrickknight',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-20-github-copilot-chat-beta-now-available-for-every-organization',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/mariorod',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-28-closing-vulnerabilities-in-decidim-a-ruby-based-citizen-participation-platform',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/stockli',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-18-security-alert-social-engineering-campaign-targets-technology-industry-employees',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/alexiswales',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-12-introducing-passwordless-authentication-on-github-com',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-26-how-to-get-ai-regulation-right-for-open-source',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/pcihon',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-05-introduction-to-selinux',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/kwstubbs',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-05-12-how-i-used-github-copilot-to-build-a-browser-extension',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-05-05-building-a-more-inclusive-github-global-campus',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/arelia',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-12-no-cyber-resilience-without-open-source-sustainability',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/mlinksva',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-06-19-developers-need-the-right-to-challenge-junk-patents',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-19-exploring-developer-happiness-inclusion-and-productivity-at-githubs-design-conference',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/amandaswan',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-17-prompt-engineering-guide-generative-ai-llms',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/wunderalbert',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/jnbrymn',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/2023-07-12-github-merge-queue-is-generally-available',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.blog/author/aspeckofdustin',
            group: 4,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/site/privacy',
            group: 20,
            distanceGroup: 0,
            explored: false,
        },
        {
            id: 'https://www.developer.github.com/',
            group: 26,
            distanceGroup: 24,
            explored: false,
        },
        { id: 'https://www.atom.io/', group: 27, distanceGroup: 25, explored: false },
        {
            id: 'https://www.support.github.com/',
            group: 11,
            distanceGroup: 25,
            explored: false,
        },
        {
            id: 'https://www.docs.github.com/en/github/site-policy/github-terms-of-service',
            group: 0,
            distanceGroup: 25,
            explored: false,
        },
        {
            id: 'https://www.docs.github.com/en/github/site-policy/github-privacy-statement',
            group: 0,
            distanceGroup: 4,
            explored: false,
        },
    ],
    links: [
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/signup?ref_cta=Sign%20up,ref_loc=header%20logged%20out,ref_page=/,source=header-home',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/actions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/packages',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/security',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/codespaces',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/code-review',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/issues',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/discussions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.docs.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.skills.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.blog/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/team',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/enterprise/startups',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.education.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/solutions/ci-cd',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.resources.github.com/devops',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.resources.github.com/devops/fundamentals/devsecops',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/customer-stories',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.resources.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.partner.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sponsors',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/readme',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/topics',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/trending',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/collections',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/pricing',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/login',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/signup?ref_cta=Sign%20up,ref_loc=header%20logged%20out,ref_page=/,source=header-home',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/preview/copilot-x',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=Home%20campaign%20hero,ref_page=/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=homepage%20sticky%20nav,ref_page=/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/join?ref_cta=Sign%20up%20for%20GitHub,ref_loc=homepage%20sticky%20nav,ref_page=/,source=homepage-sticky-nav',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/codespaces',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/actions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/mobile',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/issues',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/discussions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/code-review',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sponsors',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/kazupon',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/dayhaysoos',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/homebrew',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/eslint',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/commandpost',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sindresorhus',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/directus',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/yyx990803',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/prophen',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/security',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/security/code',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/security/software-supply-chain',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.resources.github.com/security/sast',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/signup?ref_cta=Sign%20up%20for%20GitHub,ref_loc=Home%20campaign%20footer,ref_page=/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start%20a%20free%20enterprise%20trial,ref_loc=Home%20campaign%20footer,ref_page=/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.resources.github.com/newsletter',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/security',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/team',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/customer-stories?type=enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/readme',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/pricing',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.resources.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/github/roadmap',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.resources.github.com/devops/tools/compare',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.docs.github.com/get-started/exploring-integrations/about-building-integrations',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.partner.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.electronjs.org/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.desktop.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.docs.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.community/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.services.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/premium-support',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.skills.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.githubstatus.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.support.github.com/?tags=dotcom-footer',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/about',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.blog/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/about/careers',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/about/press',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/about/diversity',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.socialimpact.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.shop.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.twitter.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.facebook.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.linkedin.com/company/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.youtube.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.twitch.tv/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.tiktok.com/@github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.docs.github.com/site-policy/github-terms/github-terms-of-service',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.docs.github.com/site-policy/privacy-policies/github-privacy-statement',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/github/site-policy/pull/582',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sitemap',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/git-guides',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/engineering',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/product',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/security',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/open-source',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/changelog',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/community',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/education',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/company',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/policy',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/enterprise/trial?ref_cta=free%20trial,ref_loc=banner,ref_page=blog',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/enterprise/contact?ref_cta=contact%20sales,ref_loc=banner,ref_page=blog',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/open-source',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nyczain',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/courtneycl',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nyczain',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/courtneycl',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/community',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/thejillboss',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-github-availability-report-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/engineering',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-github-availability-report-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jakuboleksy',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/open-source',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jarlob',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/kevinbackhouse',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-08-a-guide-to-designing-and-shipping-ai-developer-tools',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/product',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-08-a-guide-to-designing-and-shipping-ai-developer-tools',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nicchoi29',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-04-a-checklist-and-guide-to-get-your-repository-collaboration-ready',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-04-a-checklist-and-guide-to-get-your-repository-collaboration-ready',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/peckjon',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/engineering',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-03-introducing-code-referencing-for-github-copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/ryanjsalva',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-02-best-practices-for-organizations-and-teams-using-github-enterprise-cloud',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/davelosert',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/elizabethbarrord',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/engineering',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-02-how-we-build-containerized-services-at-github-using-github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/mvkaran',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/kagamicat',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/category/product',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-28-smarter-more-efficient-coding-github-copilot-goes-beyond-codex-with-improved-ai-model',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/shuyinzjk',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/changelog',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/changelog/2023-08-14-new-dataflow-api-for-writing-custom-codeql-queries',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/changelog/2023-08-11-github-copilot-august-10th-update',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/changelog/2023-08-11-secret-scanning-supports-on-demand-token-validity-checks',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/changelog/2023-08-10-ignore-or-unignore-updates-for-grouped-dependabot-pull-requests',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/changelog',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-github-availability-report-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-github-availability-report-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jakuboleksy',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jakuboleksy',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-03-introducing-code-referencing-for-github-copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/ryanjsalva',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-02-how-we-build-containerized-services-at-github-using-github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/mvkaran',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/kagamicat',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-27-scaling-merge-ort-across-github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/vtbassmatt',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/thejillboss',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/thejillboss',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-25-game-bytes-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/leereilly',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-13-release-radar-spring-23',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/mishmanners',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-13-decoding-conventions',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/martinwoodward',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nerdneha',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-03-introducing-code-referencing-for-github-copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/ryanjsalva',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/bdougie',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/lauraleap',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/hpsin',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-06-20-how-to-write-better-prompts-for-github-copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/blackgirlbytes',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/mishmanners',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2022-09-07-research-quantifying-github-copilots-impact-on-developer-productivity-and-happiness',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/ikaliam',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nyczain',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/courtneycl',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-08-a-guide-to-designing-and-shipping-ai-developer-tools',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-08-a-guide-to-designing-and-shipping-ai-developer-tools',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nicchoi29',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nicchoi29',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-04-a-checklist-and-guide-to-get-your-repository-collaboration-ready',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/peckjon',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-03-introducing-code-referencing-for-github-copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/ryanjsalva',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-28-smarter-more-efficient-coding-github-copilot-goes-beyond-codex-with-improved-ai-model',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/shuyinzjk',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-25-how-to-responsibly-adopt-github-copilot-with-the-github-copilot-trust-center',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/shellsmck',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-24-github-repository-rules-are-now-generally-available',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-24-github-repository-rules-are-now-generally-available',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/patrickknight',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-20-github-copilot-chat-beta-now-available-for-every-organization',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-20-github-copilot-chat-beta-now-available-for-every-organization',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/mariorod',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-14-nine-years-of-the-github-security-bug-bounty-program',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/thejillboss',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/thejillboss',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nyczain',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/courtneycl',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jarlob',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/kevinbackhouse',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-28-closing-vulnerabilities-in-decidim-a-ruby-based-citizen-participation-platform',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/stockli',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-24-github-repository-rules-are-now-generally-available',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/patrickknight',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-18-security-alert-social-engineering-campaign-targets-technology-industry-employees',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-18-security-alert-social-engineering-campaign-targets-technology-industry-employees',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/alexiswales',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-12-introducing-passwordless-authentication-on-github-com',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-12-introducing-passwordless-authentication-on-github-com',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/hpsin',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-enhanced-push-protection-features-for-developers-and-organizations',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nyczain',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/courtneycl',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/nyczain',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/courtneycl',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jarlob',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/kevinbackhouse',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-27-scaling-merge-ort-across-github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-27-scaling-merge-ort-across-github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/vtbassmatt',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-26-how-to-get-ai-regulation-right-for-open-source',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-26-how-to-get-ai-regulation-right-for-open-source',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/pcihon',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-25-game-bytes-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-25-game-bytes-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/leereilly',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-github-availability-report-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-09-github-availability-report-july-2023',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jakuboleksy',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-04-a-checklist-and-guide-to-get-your-repository-collaboration-ready',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/peckjon',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-08-02-best-practices-for-organizations-and-teams-using-github-enterprise-cloud',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/davelosert',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/elizabethbarrord',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-05-introduction-to-selinux',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-05-introduction-to-selinux',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/kwstubbs',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-05-12-how-i-used-github-copilot-to-build-a-browser-extension',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/blackgirlbytes',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-05-05-building-a-more-inclusive-github-global-campus',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/arelia',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-26-how-to-get-ai-regulation-right-for-open-source',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-26-how-to-get-ai-regulation-right-for-open-source',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/pcihon',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-12-no-cyber-resilience-without-open-source-sustainability',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/mlinksva',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-06-19-developers-need-the-right-to-challenge-junk-patents',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/mlinksva',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-19-exploring-developer-happiness-inclusion-and-productivity-at-githubs-design-conference',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-19-exploring-developer-happiness-inclusion-and-productivity-at-githubs-design-conference',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/amandaswan',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-17-prompt-engineering-guide-generative-ai-llms',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/wunderalbert',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/jnbrymn',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/2023-07-12-github-merge-queue-is-generally-available',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/author/aspeckofdustin',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/site/privacy',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/features',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/security',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/customer-stories?type=enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/pricing',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.resources.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.developer.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.partner.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.atom.io/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.electronjs.org/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.desktop.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.docs.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.community/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.services.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.githubstatus.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.support.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/about',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.blog/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/about/careers',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/about/press',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.shop.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.twitter.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.facebook.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.youtube.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.twitch.tv/github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.tiktok.com/@github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.linkedin.com/company/github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.github.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.docs.github.com/en/github/site-policy/github-terms-of-service',
            strength: 1,
        },
        {
            source: 'https://www.github.blog/',
            target: 'https://www.docs.github.com/en/github/site-policy/github-privacy-statement',
            strength: 1,
        },
    ],
};

// function clearGraphData(g) {
//     return JSON.stringify({
//         nodes: g.nodes.map((n) => ({
//             id: n.id,
//             group: n.group,
//             distanceGroup: n.distanceGroup,
//             explored: n.explored,
//         })),
//         links: g.links.map((l) => ({
//             source: l.source.id,
//             target: l.target.id,
//             strength: l.strength,
//         })),
//     });
// }

// console.log(clearGraphData(graphDataExample1));
