export const crawlDataExample2 = {
    explored: {
        'https://www.mdn.com/': true,
        'https://www.mdn.com/?new_locale=zh-cn&': true,
        'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
    },
    addedNodes: {
        'https://www.mdn.com/': true,
        'https://www.trustpilot.com/review/dan.com': true,
        'https://dan.com/trust_and_security?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://www.mdn.com/cookies': true,
        'https://dan.com/disclaimer?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/sitemap?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://www.mdn.com/?new_locale=nl-nl&': true,
        'https://www.mdn.com/?new_locale=es-es&': true,
        'https://www.mdn.com/?new_locale=hi-in&': true,
        'https://www.mdn.com/?new_locale=de-de&': true,
        'https://www.mdn.com/?new_locale=fr-fr&': true,
        'https://www.mdn.com/?new_locale=zh-cn&': true,
        'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/': true,
        'https://dan.com/buy_a_domain': true,
        'https://dan.com/sell_your_domain': true,
        'https://dan.pr.co/': true,
        'https://dan.com/trust_and_security': true,
        'https://dan.com/help_center': true,
        'https://dan.com/transaction_explorer': true,
        'https://dan.com/our_story': true,
        'https://dan.com/api_partnership_program': true,
        'https://dan.com/careers': true,
        'https://dan.com/contact': true,
        'https://dan.com/users/login': true,
        'https://dan.com/privacy?archive=2022-12-22': true,
        'https://dan.com/cookies': true,
        'https://allaboutdnt.com/': true,
        'https://dan.com/brokerage': true,
        'https://twitter.com/undeveloped': true,
        'https://domaining.com/feed/dan/': true,
        'https://www.linkedin.com/company/dan-com': true,
        'https://blog.undeveloped.com/': true,
        'https://dan.com/privacy': true,
        'https://dan.com/terms_of_use': true,
        'https://dan.com/disclaimer': true,
        'https://dan.com/sitemap': true,
        'https://dan.com/privacy?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/privacy?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/privacy?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/privacy?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/privacy?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/privacy?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/search?order_by=views-desc&popular=true&terms=%2A': true,
        'https://dan.com/search?no_hyphens=true&no_numerals=true&no_unicode=true&order_by=views-desc&terms=%2A&three_digits=true&tld%5B%5D=com': true,
        'https://dan.com/search?order_by=views-desc&premium=true&terms=%2A&tld%5B%5D=com&tld%5B%5D=co&tld%5B%5D=ai&tld%5B%5D=io&tld%5B%5D=xyz': true,
        'https://dan.com/?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://supportcenter.godaddy.com/AbuseReport': true,
        'https://www.godaddy.com/en-uk/legal/agreements/trademark-copyright-infringement': true,
        'https://dan.com/terms_of_use?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/terms_of_use?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/terms_of_use?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/terms_of_use?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/terms_of_use?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
        'https://dan.com/terms_of_use?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com': true,
    },
    groups: [
        'dan.com',
        'www.trustpilot.com',
        'dan.pr.co',
        'allaboutdnt.com',
        'twitter.com',
        'domaining.com',
        'www.linkedin.com',
        'blog.undeveloped.com',
        'supportcenter.godaddy.com',
        'www.godaddy.com',
    ],
};

export const graphDataExample2 = {
    nodes: [
        { id: 'https://www.mdn.com/', group: 1, distanceGroup: 1, explored: true },
        {
            id: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 3,
            explored: true,
        },
        {
            id: 'https://www.trustpilot.com/review/dan.com',
            group: 3,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://dan.com/trust_and_security?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: true,
        },
        {
            id: 'https://www.mdn.com/cookies',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: true,
        },
        {
            id: 'https://dan.com/disclaimer?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://dan.com/sitemap?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=nl-nl&',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=es-es&',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=hi-in&',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=de-de&',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=fr-fr&',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=zh-cn&',
            group: 1,
            distanceGroup: 1,
            explored: true,
        },
        { id: 'https://dan.com/', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://dan.com/buy_a_domain',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/sell_your_domain',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://dan.pr.co/', group: 5, distanceGroup: 5, explored: false },
        {
            id: 'https://dan.com/trust_and_security',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/help_center',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/transaction_explorer',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://dan.com/our_story', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://dan.com/api_partnership_program',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://dan.com/careers', group: 2, distanceGroup: 1, explored: false },
        { id: 'https://dan.com/contact', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://dan.com/users/login',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/privacy?archive=2022-12-22',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://dan.com/cookies', group: 2, distanceGroup: 1, explored: false },
        { id: 'https://allaboutdnt.com/', group: 6, distanceGroup: 6, explored: false },
        { id: 'https://dan.com/brokerage', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://twitter.com/undeveloped',
            group: 7,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://domaining.com/feed/dan/',
            group: 8,
            distanceGroup: 8,
            explored: false,
        },
        {
            id: 'https://www.linkedin.com/company/dan-com',
            group: 9,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://blog.undeveloped.com/',
            group: 10,
            distanceGroup: 10,
            explored: false,
        },
        { id: 'https://dan.com/privacy', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://dan.com/terms_of_use',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://dan.com/disclaimer', group: 2, distanceGroup: 1, explored: false },
        { id: 'https://dan.com/sitemap', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://dan.com/privacy?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/privacy?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/privacy?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/privacy?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/privacy?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/privacy?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/search?order_by=views-desc&popular=true&terms=%2A',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/search?no_hyphens=true&no_numerals=true&no_unicode=true&order_by=views-desc&terms=%2A&three_digits=true&tld%5B%5D=com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/search?order_by=views-desc&premium=true&terms=%2A&tld%5B%5D=com&tld%5B%5D=co&tld%5B%5D=ai&tld%5B%5D=io&tld%5B%5D=xyz',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://supportcenter.godaddy.com/AbuseReport',
            group: 11,
            distanceGroup: 11,
            explored: false,
        },
        {
            id: 'https://www.godaddy.com/en-uk/legal/agreements/trademark-copyright-infringement',
            group: 12,
            distanceGroup: 12,
            explored: false,
        },
        {
            id: 'https://dan.com/terms_of_use?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/terms_of_use?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/terms_of_use?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/terms_of_use?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/terms_of_use?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://dan.com/terms_of_use?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
    ],
    links: [
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.trustpilot.com/review/dan.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/trust_and_security?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.mdn.com/cookies',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/disclaimer?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://dan.com/sitemap?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.mdn.com/?new_locale=nl-nl&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.mdn.com/?new_locale=es-es&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.mdn.com/?new_locale=hi-in&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.mdn.com/?new_locale=de-de&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.mdn.com/?new_locale=fr-fr&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/',
            target: 'https://www.mdn.com/?new_locale=zh-cn&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.trustpilot.com/review/dan.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/trust_and_security?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.mdn.com/cookies',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/disclaimer?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://dan.com/sitemap?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.mdn.com/?new_locale=nl-nl&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.mdn.com/?new_locale=es-es&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.mdn.com/?new_locale=hi-in&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.mdn.com/?new_locale=de-de&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.mdn.com/?new_locale=fr-fr&',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn&',
            target: 'https://www.mdn.com/?new_locale=zh-cn&',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/users/login',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/users/login',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy?archive=2022-12-22',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/cookies',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://allaboutdnt.com/',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/brokerage',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://twitter.com/undeveloped',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://domaining.com/feed/dan/',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://www.linkedin.com/company/dan-com',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://blog.undeveloped.com/',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/cookies',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/disclaimer',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sitemap',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/privacy?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/users/login',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/users/login',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/search?order_by=views-desc&popular=true&terms=%2A',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/search?no_hyphens=true&no_numerals=true&no_unicode=true&order_by=views-desc&terms=%2A&three_digits=true&tld%5B%5D=com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/search?order_by=views-desc&premium=true&terms=%2A&tld%5B%5D=com&tld%5B%5D=co&tld%5B%5D=ai&tld%5B%5D=io&tld%5B%5D=xyz',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/brokerage',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://twitter.com/undeveloped',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://domaining.com/feed/dan/',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://www.linkedin.com/company/dan-com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://blog.undeveloped.com/',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/cookies',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/disclaimer',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sitemap',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/users/login',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/users/login',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/cookies',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/disclaimer',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://supportcenter.godaddy.com/AbuseReport',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://www.godaddy.com/en-uk/legal/agreements/trademark-copyright-infringement',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/buy_a_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sell_your_domain',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/api_partnership_program',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/brokerage',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.pr.co/',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/trust_and_security',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/help_center',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/transaction_explorer',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/careers',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/our_story',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/contact',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://twitter.com/undeveloped',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://domaining.com/feed/dan/',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://www.linkedin.com/company/dan-com',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://blog.undeveloped.com/',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/privacy',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/cookies',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/disclaimer',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/sitemap',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use?new_locale=nl-nl&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use?new_locale=es-es&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use?new_locale=hi-in&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use?new_locale=de-de&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use?new_locale=fr-fr&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://dan.com/terms_of_use?utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            target: 'https://dan.com/terms_of_use?new_locale=zh-cn&utm_campaign=Parking&utm_medium=parking&utm_source=.com&utm_term=mdn.com',
            strength: 1,
        },
    ],
};

// function clearGraphData(g) {
//     return JSON.stringify({
//         nodes: g.nodes.map((n) => ({
//             id: n.id,
//             group: n.group,
//             distanceGroup: n.distanceGroup,
//             explored: n.explored,
//         })),
//         links: g.links.map((l) => ({
//             source: l.source.id,
//             target: l.target.id,
//             strength: l.strength,
//         })),
//     });
// }

// console.log(clearGraphData(graphDataExample3));
