export const crawlDataExample2 = {
    explored: {
        'https://www.google.com/': true,
        'https://www.google.com/imghp?hl=en,tab=wi': true,
        'https://www.google.com/webhp?tab=iw': true,
    },
    addedNodes: {
        'https://www.google.com/': true,
        'https://www.maps.google.com/maps?hl=en,tab=wl': true,
        'https://www.play.google.com/?hl=en,tab=w8': true,
        'https://www.youtube.com/?tab=w1': true,
        'https://www.news.google.com/?tab=wn': true,
        'https://www.mail.google.com/mail?tab=wm': true,
        'https://www.drive.google.com/?tab=wo': true,
        'https://www.google.com/intl/en/about/products?tab=wh': true,
        'http://www.google.com/history/optout?hl=en': true,
        'https://www.google.com/preferences?hl=en': true,
        'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/,ec=GAZAAQ,hl=en,passive=true': true,
        'https://www.google.com/advanced_search?authuser=0,hl=en': true,
        'https://www.google.com/intl/en/ads': true,
        'https://www.google.com/services': true,
        'https://www.google.com/intl/en/about.html': true,
        'https://www.google.com/intl/en/policies/privacy': true,
        'https://www.google.com/intl/en/policies/terms': true,
        'https://www.google.com/imghp?hl=en,tab=wi': true,
        'https://www.maps.google.com/maps?hl=en,tab=il': true,
        'https://www.play.google.com/?hl=en,tab=i8': true,
        'https://www.youtube.com/?tab=i1': true,
        'https://www.news.google.com/?tab=in': true,
        'https://www.mail.google.com/mail?tab=im': true,
        'https://www.drive.google.com/?tab=io': true,
        'https://www.google.com/intl/en/about/products?tab=ih': true,
        'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/imghp?hl=en,tab=wi,ec=GAZAAg,hl=en,passive=true': true,
        'https://www.google.com/advanced_image_search?authuser=0,hl=en': true,
        'https://www.google.com/webhp?tab=iw': true,
        'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/webhp?tab=iw,ec=GAZAAQ,hl=en,passive=true': true,
    },
    groups: [
        'www.maps.google.com',
        'www.play.google.com',
        'www.youtube.com',
        'www.news.google.com',
        'www.mail.google.com',
        'www.drive.google.com',
        'www.accounts.google.com',
    ],
};

export const graphDataExample2 = {
    nodes: [
        { id: 'https://www.google.com/', group: 1, distanceGroup: 1, explored: true },
        {
            id: 'https://www.google.com/imghp?hl=en,tab=wi',
            group: 1,
            distanceGroup: 1,
            explored: true,
        },
        {
            id: 'https://www.maps.google.com/maps?hl=en,tab=wl',
            group: 2,
            distanceGroup: 3,
            explored: false,
        },
        {
            id: 'https://www.play.google.com/?hl=en,tab=w8',
            group: 3,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://www.youtube.com/?tab=w1',
            group: 4,
            distanceGroup: 5,
            explored: false,
        },
        {
            id: 'https://www.news.google.com/?tab=wn',
            group: 5,
            distanceGroup: 6,
            explored: false,
        },
        {
            id: 'https://www.mail.google.com/mail?tab=wm',
            group: 6,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://www.drive.google.com/?tab=wo',
            group: 7,
            distanceGroup: 8,
            explored: false,
        },
        {
            id: 'https://www.google.com/intl/en/about/products?tab=wh',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'http://www.google.com/history/optout?hl=en',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.google.com/preferences?hl=en',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/,ec=GAZAAQ,hl=en,passive=true',
            group: 8,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.google.com/advanced_search?authuser=0,hl=en',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.google.com/intl/en/ads',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.google.com/services',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.google.com/intl/en/about.html',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.google.com/intl/en/policies/privacy',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.google.com/intl/en/policies/terms',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.google.com/webhp?tab=iw',
            group: 1,
            distanceGroup: 1,
            explored: true,
        },
        {
            id: 'https://www.maps.google.com/maps?hl=en,tab=il',
            group: 0,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.play.google.com/?hl=en,tab=i8',
            group: 1,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.youtube.com/?tab=i1',
            group: 2,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.news.google.com/?tab=in',
            group: 3,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.mail.google.com/mail?tab=im',
            group: 4,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.drive.google.com/?tab=io',
            group: 5,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.google.com/intl/en/about/products?tab=ih',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/imghp?hl=en,tab=wi,ec=GAZAAg,hl=en,passive=true',
            group: 6,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.google.com/advanced_image_search?authuser=0,hl=en',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/webhp?tab=iw,ec=GAZAAQ,hl=en,passive=true',
            group: 6,
            distanceGroup: 9,
            explored: false,
        },
    ],
    links: [
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/imghp?hl=en,tab=wi',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.maps.google.com/maps?hl=en,tab=wl',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.play.google.com/?hl=en,tab=w8',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.youtube.com/?tab=w1',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.news.google.com/?tab=wn',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.mail.google.com/mail?tab=wm',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.drive.google.com/?tab=wo',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/intl/en/about/products?tab=wh',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'http://www.google.com/history/optout?hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/preferences?hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/,ec=GAZAAQ,hl=en,passive=true',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/advanced_search?authuser=0,hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/intl/en/ads',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/services',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/intl/en/about.html',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/intl/en/policies/privacy',
            strength: 1,
        },
        {
            source: 'https://www.google.com/',
            target: 'https://www.google.com/intl/en/policies/terms',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/webhp?tab=iw',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.maps.google.com/maps?hl=en,tab=il',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.play.google.com/?hl=en,tab=i8',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.youtube.com/?tab=i1',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.news.google.com/?tab=in',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.mail.google.com/mail?tab=im',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.drive.google.com/?tab=io',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/intl/en/about/products?tab=ih',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'http://www.google.com/history/optout?hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/preferences?hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/imghp?hl=en,tab=wi,ec=GAZAAg,hl=en,passive=true',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/advanced_image_search?authuser=0,hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/intl/en/ads',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/services',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/intl/en/about.html',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/intl/en/policies/privacy',
            strength: 1,
        },
        {
            source: 'https://www.google.com/imghp?hl=en,tab=wi',
            target: 'https://www.google.com/intl/en/policies/terms',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/imghp?hl=en,tab=wi',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.maps.google.com/maps?hl=en,tab=wl',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.play.google.com/?hl=en,tab=w8',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.youtube.com/?tab=w1',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.news.google.com/?tab=wn',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.mail.google.com/mail?tab=wm',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.drive.google.com/?tab=wo',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/intl/en/about/products?tab=wh',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'http://www.google.com/history/optout?hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/preferences?hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.accounts.google.com/servicelogin?continue=https://www.google.com/webhp?tab=iw,ec=GAZAAQ,hl=en,passive=true',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/advanced_search?authuser=0,hl=en',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/intl/en/ads',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/services',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/intl/en/about.html',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/intl/en/policies/privacy',
            strength: 1,
        },
        {
            source: 'https://www.google.com/webhp?tab=iw',
            target: 'https://www.google.com/intl/en/policies/terms',
            strength: 1,
        },
    ],
};

// function clearGraphData(g) {
//     return JSON.stringify({
//         nodes: g.nodes.map((n) => ({
//             id: n.id,
//             group: n.group,
//             distanceGroup: n.distanceGroup,
//             explored: n.explored,
//         })),
//         links: g.links.map((l) => ({
//             source: l.source.id,
//             target: l.target.id,
//             strength: l.strength,
//         })),
//     });
// }

// console.log(clearGraphData(graphDataExample2));
