export const crawlDataExample1 = {
    explored: {
        'https://www.github.com/': true,
        'https://github.com/': true,
    },
    addedNodes: {
        'https://www.github.com/': true,
        'https://www.github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home': true,
        'https://www.github.com/features/actions': true,
        'https://www.github.com/features/packages': true,
        'https://www.github.com/features/security': true,
        'https://www.github.com/features/codespaces': true,
        'https://www.github.com/features/copilot': true,
        'https://www.github.com/features/code-review': true,
        'https://www.github.com/features/issues': true,
        'https://www.github.com/features/discussions': true,
        'https://www.github.com/features': true,
        'https://docs.github.com/': true,
        'https://skills.github.com/': true,
        'https://github.blog/': true,
        'https://www.github.com/enterprise': true,
        'https://www.github.com/team': true,
        'https://www.github.com/enterprise/startups': true,
        'https://education.github.com/': true,
        'https://www.github.com/solutions/ci-cd/': true,
        'https://resources.github.com/devops/': true,
        'https://resources.github.com/devops/fundamentals/devsecops/': true,
        'https://www.github.com/customer-stories': true,
        'https://resources.github.com/': true,
        'https://partner.github.com/': true,
        'https://www.github.com/sponsors': true,
        'https://www.github.com/readme': true,
        'https://www.github.com/topics': true,
        'https://www.github.com/trending': true,
        'https://www.github.com/collections': true,
        'https://www.github.com/pricing': true,
        'https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax': true,
        'https://www.github.com/login': true,
        'https://www.github.com/features/preview/copilot-x': true,
        'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+hero&ref_page=%2F': true,
        'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=homepage+sticky+nav&ref_page=%2F': true,
        'https://www.github.com/join?ref_cta=Sign+up+for+GitHub&ref_loc=homepage+sticky+nav&ref_page=%2F&source=homepage-sticky-nav': true,
        'https://www.github.com/mobile': true,
        'https://www.github.com/imolorhe': true,
        'https://www.github.com/kazupon': true,
        'https://www.github.com/prophen': true,
        'https://www.github.com/directus': true,
        'https://www.github.com/commandpost': true,
        'https://www.github.com/dayhaysoos': true,
        'https://www.github.com/homebrew': true,
        'https://www.github.com/chaynhq': true,
        'https://www.github.com/sindresorhus': true,
        'https://github.com/features/security/code': true,
        'https://www.github.com/features/security/software-supply-chain': true,
        'https://resources.github.com/security/sast/': true,
        'https://www.github.com/signup?ref_cta=Sign+up+for+GitHub&ref_loc=Home+campaign+footer&ref_page=%2F': true,
        'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+footer&ref_page=%2F': true,
        'https://resources.github.com/newsletter/': true,
        'https://www.github.com/security': true,
        'https://www.github.com/customer-stories?type=enterprise': true,
        'https://github.com/github/roadmap': true,
        'https://resources.github.com/devops/tools/compare/': true,
        'https://docs.github.com/get-started/exploring-integrations/about-building-integrations': true,
        'https://www.electronjs.org/': true,
        'https://desktop.github.com/': true,
        'https://github.community/': true,
        'https://services.github.com/': true,
        'https://www.github.com/premium-support': true,
        'https://www.githubstatus.com/': true,
        'https://support.github.com/?tags=dotcom-footer': true,
        'https://github.com/about': true,
        'https://www.github.com/about/careers': true,
        'https://www.github.com/about/press': true,
        'https://www.github.com/about/diversity': true,
        'https://socialimpact.github.com/': true,
        'https://shop.github.com/': true,
        'https://twitter.com/github': true,
        'https://www.facebook.com/GitHub': true,
        'https://www.linkedin.com/company/github': true,
        'https://www.youtube.com/github': true,
        'https://www.twitch.tv/github': true,
        'https://www.tiktok.com/@github': true,
        'https://github.com/github': true,
        'https://docs.github.com/site-policy/github-terms/github-terms-of-service': true,
        'https://docs.github.com/site-policy/privacy-policies/github-privacy-statement': true,
        'https://github.com/github/site-policy/pull/582': true,
        'https://www.github.com/sitemap': true,
        'https://www.github.com/git-guides': true,
        'https://github.com/': true,
        'https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home': true,
        'https://github.com/features/actions': true,
        'https://github.com/features/packages': true,
        'https://github.com/features/security': true,
        'https://github.com/features/codespaces': true,
        'https://github.com/features/copilot': true,
        'https://github.com/features/code-review': true,
        'https://github.com/features/issues': true,
        'https://github.com/features/discussions': true,
        'https://github.com/features': true,
        'https://github.com/enterprise': true,
        'https://github.com/team': true,
        'https://github.com/enterprise/startups': true,
        'https://github.com/solutions/ci-cd/': true,
        'https://github.com/customer-stories': true,
        'https://github.com/sponsors': true,
        'https://github.com/readme': true,
        'https://github.com/topics': true,
        'https://github.com/trending': true,
        'https://github.com/collections': true,
        'https://github.com/pricing': true,
        'https://github.com/login': true,
        'https://github.com/features/preview/copilot-x': true,
        'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+hero&ref_page=%2F': true,
        'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=homepage+sticky+nav&ref_page=%2F': true,
        'https://github.com/join?ref_cta=Sign+up+for+GitHub&ref_loc=homepage+sticky+nav&ref_page=%2F&source=homepage-sticky-nav': true,
        'https://github.com/mobile': true,
        'https://github.com/imolorhe': true,
        'https://github.com/kazupon': true,
        'https://github.com/prophen': true,
        'https://github.com/directus': true,
        'https://github.com/commandpost': true,
        'https://github.com/dayhaysoos': true,
        'https://github.com/homebrew': true,
        'https://github.com/chaynhq': true,
        'https://github.com/sindresorhus': true,
        'https://github.com/features/security/software-supply-chain': true,
        'https://github.com/signup?ref_cta=Sign+up+for+GitHub&ref_loc=Home+campaign+footer&ref_page=%2F': true,
        'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+footer&ref_page=%2F': true,
        'https://github.com/security': true,
        'https://github.com/customer-stories?type=enterprise': true,
        'https://github.com/premium-support': true,
        'https://github.com/about/careers': true,
        'https://github.com/about/press': true,
        'https://github.com/about/diversity': true,
        'https://github.com/sitemap': true,
        'https://github.com/git-guides': true,
    },
    groups: [
        'github.com',
        'docs.github.com',
        'skills.github.com',
        'github.blog',
        'education.github.com',
        'resources.github.com',
        'partner.github.com',
        'www.electronjs.org',
        'desktop.github.com',
        'github.community',
        'services.github.com',
        'www.githubstatus.com',
        'support.github.com',
        'socialimpact.github.com',
        'shop.github.com',
        'twitter.com',
        'www.facebook.com',
        'www.linkedin.com',
        'www.youtube.com',
        'www.twitch.tv',
        'www.tiktok.com',
    ],
};

export const graphDataExample1 = {
    nodes: [
        { id: 'https://www.github.com/', group: 1, distanceGroup: 1, explored: true },
        { id: 'https://github.com/', group: 2, distanceGroup: 3, explored: true },
        {
            id: 'https://www.github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/actions',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/packages',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/security',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/codespaces',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/copilot',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/code-review',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/issues',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/discussions',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://docs.github.com/', group: 3, distanceGroup: 4, explored: false },
        { id: 'https://skills.github.com/', group: 4, distanceGroup: 5, explored: false },
        { id: 'https://github.blog/', group: 5, distanceGroup: 6, explored: false },
        {
            id: 'https://www.github.com/enterprise',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/team',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/enterprise/startups',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://education.github.com/',
            group: 6,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://www.github.com/solutions/ci-cd/',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://resources.github.com/devops/',
            group: 7,
            distanceGroup: 8,
            explored: false,
        },
        {
            id: 'https://resources.github.com/devops/fundamentals/devsecops/',
            group: 7,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://www.github.com/customer-stories',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://resources.github.com/',
            group: 7,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://partner.github.com/',
            group: 8,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.github.com/sponsors',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/readme',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/topics',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/trending',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/collections',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/pricing',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            group: 3,
            distanceGroup: 3,
            explored: false,
        },
        {
            id: 'https://www.github.com/login',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/preview/copilot-x',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+hero&ref_page=%2F',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=homepage+sticky+nav&ref_page=%2F',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/join?ref_cta=Sign+up+for+GitHub&ref_loc=homepage+sticky+nav&ref_page=%2F&source=homepage-sticky-nav',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/mobile',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/imolorhe',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/kazupon',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/prophen',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/directus',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/commandpost',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/dayhaysoos',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/homebrew',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/chaynhq',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/sindresorhus',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/security/code',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://www.github.com/features/security/software-supply-chain',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://resources.github.com/security/sast/',
            group: 7,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://www.github.com/signup?ref_cta=Sign+up+for+GitHub&ref_loc=Home+campaign+footer&ref_page=%2F',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+footer&ref_page=%2F',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://resources.github.com/newsletter/',
            group: 7,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://www.github.com/security',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/customer-stories?type=enterprise',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/github/roadmap',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://resources.github.com/devops/tools/compare/',
            group: 7,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://docs.github.com/get-started/exploring-integrations/about-building-integrations',
            group: 3,
            distanceGroup: 3,
            explored: false,
        },
        {
            id: 'https://www.electronjs.org/',
            group: 9,
            distanceGroup: 10,
            explored: false,
        },
        {
            id: 'https://desktop.github.com/',
            group: 10,
            distanceGroup: 11,
            explored: false,
        },
        {
            id: 'https://github.community/',
            group: 11,
            distanceGroup: 12,
            explored: false,
        },
        {
            id: 'https://services.github.com/',
            group: 12,
            distanceGroup: 13,
            explored: false,
        },
        {
            id: 'https://www.github.com/premium-support',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.githubstatus.com/',
            group: 13,
            distanceGroup: 14,
            explored: false,
        },
        {
            id: 'https://support.github.com/?tags=dotcom-footer',
            group: 14,
            distanceGroup: 15,
            explored: false,
        },
        { id: 'https://github.com/about', group: 2, distanceGroup: 2, explored: false },
        {
            id: 'https://www.github.com/about/careers',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/about/press',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/about/diversity',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://socialimpact.github.com/',
            group: 15,
            distanceGroup: 16,
            explored: false,
        },
        { id: 'https://shop.github.com/', group: 16, distanceGroup: 17, explored: false },
        {
            id: 'https://twitter.com/github',
            group: 17,
            distanceGroup: 18,
            explored: false,
        },
        {
            id: 'https://www.facebook.com/GitHub',
            group: 18,
            distanceGroup: 19,
            explored: false,
        },
        {
            id: 'https://www.linkedin.com/company/github',
            group: 19,
            distanceGroup: 20,
            explored: false,
        },
        {
            id: 'https://www.youtube.com/github',
            group: 20,
            distanceGroup: 21,
            explored: false,
        },
        {
            id: 'https://www.twitch.tv/github',
            group: 21,
            distanceGroup: 22,
            explored: false,
        },
        {
            id: 'https://www.tiktok.com/@github',
            group: 22,
            distanceGroup: 23,
            explored: false,
        },
        { id: 'https://github.com/github', group: 2, distanceGroup: 2, explored: false },
        {
            id: 'https://docs.github.com/site-policy/github-terms/github-terms-of-service',
            group: 3,
            distanceGroup: 3,
            explored: false,
        },
        {
            id: 'https://docs.github.com/site-policy/privacy-policies/github-privacy-statement',
            group: 3,
            distanceGroup: 3,
            explored: false,
        },
        {
            id: 'https://github.com/github/site-policy/pull/582',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://www.github.com/sitemap',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.github.com/git-guides',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/actions',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/packages',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/security',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/codespaces',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/copilot',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/code-review',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/issues',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/discussions',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/enterprise',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://github.com/team', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://github.com/enterprise/startups',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/solutions/ci-cd/',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/customer-stories',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/sponsors',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://github.com/readme', group: 2, distanceGroup: 1, explored: false },
        { id: 'https://github.com/topics', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://github.com/trending',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/collections',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://github.com/pricing', group: 2, distanceGroup: 1, explored: false },
        { id: 'https://github.com/login', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://github.com/features/preview/copilot-x',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+hero&ref_page=%2F',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=homepage+sticky+nav&ref_page=%2F',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/join?ref_cta=Sign+up+for+GitHub&ref_loc=homepage+sticky+nav&ref_page=%2F&source=homepage-sticky-nav',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://github.com/mobile', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://github.com/imolorhe',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://github.com/kazupon', group: 2, distanceGroup: 1, explored: false },
        { id: 'https://github.com/prophen', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://github.com/directus',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/commandpost',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/dayhaysoos',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/homebrew',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://github.com/chaynhq', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://github.com/sindresorhus',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/features/security/software-supply-chain',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/signup?ref_cta=Sign+up+for+GitHub&ref_loc=Home+campaign+footer&ref_page=%2F',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+footer&ref_page=%2F',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/security',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/customer-stories?type=enterprise',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/premium-support',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/about/careers',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/about/press',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://github.com/about/diversity',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://github.com/sitemap', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://github.com/git-guides',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
    ],
    links: [
        { source: 'https://www.github.com/', target: 'https://github.com/', strength: 1 },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/actions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/packages',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/security',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/codespaces',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/code-review',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/issues',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/discussions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://docs.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://skills.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.blog/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/team',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/enterprise/startups',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://education.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/solutions/ci-cd/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://resources.github.com/devops/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://resources.github.com/devops/fundamentals/devsecops/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/customer-stories',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://resources.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://partner.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sponsors',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/readme',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/topics',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/trending',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/collections',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/pricing',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/login',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/preview/copilot-x',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+hero&ref_page=%2F',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=homepage+sticky+nav&ref_page=%2F',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/join?ref_cta=Sign+up+for+GitHub&ref_loc=homepage+sticky+nav&ref_page=%2F&source=homepage-sticky-nav',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/codespaces',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/copilot',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/actions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/mobile',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/issues',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/discussions',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/code-review',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sponsors',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/imolorhe',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/kazupon',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/prophen',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/directus',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/commandpost',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/dayhaysoos',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/homebrew',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/chaynhq',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sindresorhus',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/security',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.com/features/security/code',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features/security/software-supply-chain',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://resources.github.com/security/sast/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/signup?ref_cta=Sign+up+for+GitHub&ref_loc=Home+campaign+footer&ref_page=%2F',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+footer&ref_page=%2F',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://resources.github.com/newsletter/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/features',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/security',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/team',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/customer-stories?type=enterprise',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/readme',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/pricing',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://resources.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.com/github/roadmap',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://resources.github.com/devops/tools/compare/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://docs.github.com/get-started/exploring-integrations/about-building-integrations',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://partner.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.electronjs.org/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://desktop.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://docs.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.community/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://services.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/premium-support',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://skills.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.githubstatus.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://support.github.com/?tags=dotcom-footer',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.com/about',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.blog/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/about/careers',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/about/press',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/about/diversity',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://socialimpact.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://shop.github.com/',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://twitter.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.facebook.com/GitHub',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.linkedin.com/company/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.youtube.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.twitch.tv/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.tiktok.com/@github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.com/github',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://docs.github.com/site-policy/github-terms/github-terms-of-service',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://docs.github.com/site-policy/privacy-policies/github-privacy-statement',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://github.com/github/site-policy/pull/582',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/sitemap',
            strength: 1,
        },
        {
            source: 'https://www.github.com/',
            target: 'https://www.github.com/git-guides',
            strength: 1,
        },
        { source: 'https://github.com/', target: 'https://github.com/', strength: 1 },
        {
            source: 'https://github.com/',
            target: 'https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/actions',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/packages',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/security',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/codespaces',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/copilot',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/code-review',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/issues',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/discussions',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://docs.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://skills.github.com/',
            strength: 1,
        },
        { source: 'https://github.com/', target: 'https://github.blog/', strength: 1 },
        {
            source: 'https://github.com/',
            target: 'https://github.com/enterprise',
            strength: 1,
        },
        { source: 'https://github.com/', target: 'https://github.com/team', strength: 1 },
        {
            source: 'https://github.com/',
            target: 'https://github.com/enterprise/startups',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://education.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/solutions/ci-cd/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://resources.github.com/devops/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://resources.github.com/devops/fundamentals/devsecops/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/customer-stories',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://resources.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://partner.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/sponsors',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/readme',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/topics',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/trending',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/collections',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/pricing',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/login',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F&source=header-home',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/preview/copilot-x',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+hero&ref_page=%2F',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=homepage+sticky+nav&ref_page=%2F',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/join?ref_cta=Sign+up+for+GitHub&ref_loc=homepage+sticky+nav&ref_page=%2F&source=homepage-sticky-nav',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/codespaces',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/copilot',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/actions',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/mobile',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/issues',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/discussions',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/code-review',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/sponsors',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/imolorhe',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/kazupon',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/prophen',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/directus',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/commandpost',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/dayhaysoos',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/homebrew',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/chaynhq',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/sindresorhus',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/security',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/security/code',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features/security/software-supply-chain',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://resources.github.com/security/sast/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/signup?ref_cta=Sign+up+for+GitHub&ref_loc=Home+campaign+footer&ref_page=%2F',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/organizations/enterprise_plan?ref_cta=Start+a+free+enterprise+trial&ref_loc=Home+campaign+footer&ref_page=%2F',
            strength: 1,
        },
        { source: 'https://github.com/', target: 'https://github.com/', strength: 1 },
        {
            source: 'https://github.com/',
            target: 'https://resources.github.com/newsletter/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/features',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/security',
            strength: 1,
        },
        { source: 'https://github.com/', target: 'https://github.com/team', strength: 1 },
        {
            source: 'https://github.com/',
            target: 'https://github.com/enterprise',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/customer-stories?type=enterprise',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/readme',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/pricing',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://resources.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/github/roadmap',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://resources.github.com/devops/tools/compare/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://docs.github.com/get-started/exploring-integrations/about-building-integrations',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://partner.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://www.electronjs.org/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://desktop.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://docs.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.community/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://services.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/premium-support',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://skills.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://www.githubstatus.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://support.github.com/?tags=dotcom-footer',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/about',
            strength: 1,
        },
        { source: 'https://github.com/', target: 'https://github.blog/', strength: 1 },
        {
            source: 'https://github.com/',
            target: 'https://github.com/about/careers',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/about/press',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/about/diversity',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://socialimpact.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://shop.github.com/',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://twitter.com/github',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://www.facebook.com/GitHub',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://www.linkedin.com/company/github',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://www.youtube.com/github',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://www.twitch.tv/github',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://www.tiktok.com/@github',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/github',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://docs.github.com/site-policy/github-terms/github-terms-of-service',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://docs.github.com/site-policy/privacy-policies/github-privacy-statement',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/github/site-policy/pull/582',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/sitemap',
            strength: 1,
        },
        {
            source: 'https://github.com/',
            target: 'https://github.com/git-guides',
            strength: 1,
        },
    ],
};
