export const crawlDataExample2 = {
    explored: {
        'https://www.mdn.com/?': true,
        'https://www.mdn.com/?new_locale=zh-cn': true,
        'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/sitemap?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
    },
    addedNodes: {
        'https://www.mdn.com/?': true,
        'https://www.trustpilot.com/review/dan.com?': true,
        'https://www.dan.com/trust_and_security?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.mdn.com/cookies?': true,
        'https://www.dan.com/disclaimer?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.mdn.com/?new_locale=nl-nl': true,
        'https://www.mdn.com/?new_locale=es-es': true,
        'https://www.mdn.com/?new_locale=hi-in': true,
        'https://www.mdn.com/?new_locale=de-de': true,
        'https://www.mdn.com/?new_locale=fr-fr': true,
        'https://www.mdn.com/?new_locale=zh-cn': true,
        'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/?': true,
        'https://www.dan.com/buy_a_domain?': true,
        'https://www.dan.com/sell_your_domain?': true,
        'https://www.dan.pr.co/?': true,
        'https://www.dan.com/trust_and_security?': true,
        'https://www.dan.com/help_center?': true,
        'https://www.dan.com/transaction_explorer?': true,
        'https://www.dan.com/our_story?': true,
        'https://www.dan.com/api_partnership_program?': true,
        'https://www.dan.com/careers?': true,
        'https://www.dan.com/contact?': true,
        'https://www.dan.com/users/login?': true,
        'https://www.dan.com/search?order_by=views-desc,popular=true,terms=*': true,
        'https://www.dan.com/search?no_hyphens=true,no_numerals=true,no_unicode=true,order_by=views-desc,terms=*,three_digits=true,tld[]=com': true,
        'https://www.dan.com/search?order_by=views-desc,premium=true,terms=*,tld[]=com,tld[]=com,tld[]=com,tld[]=com,tld[]=com': true,
        'https://www.dan.com/brokerage?': true,
        'https://www.twitter.com/undeveloped?': true,
        'https://www.domaining.com/feed/dan?': true,
        'https://www.linkedin.com/company/dan-com?': true,
        'https://www.blog.undeveloped.com/?': true,
        'https://www.dan.com/privacy?': true,
        'https://www.dan.com/cookies?': true,
        'https://www.dan.com/terms_of_use?': true,
        'https://www.dan.com/disclaimer?': true,
        'https://www.dan.com/sitemap?': true,
        'https://www.dan.com/?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/sitemap?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.supportcenter.godaddy.com/abusereport?': true,
        'https://www.godaddy.com/en-uk/legal/agreements/trademark-copyright-infringement?': true,
        'https://www.dan.com/terms_of_use?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/terms_of_use?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/terms_of_use?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/terms_of_use?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/terms_of_use?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/terms_of_use?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?archive=2022-12-22': true,
        'https://www.allaboutdnt.com/?': true,
        'https://www.dan.com/privacy?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
        'https://www.dan.com/privacy?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com': true,
    },
    groups: [
        'www.dan.com',
        'www.trustpilot.com',
        'www.dan.pr.co',
        'www.twitter.com',
        'www.domaining.com',
        'www.linkedin.com',
        'www.blog.undeveloped.com',
        'www.supportcenter.godaddy.com',
        'www.godaddy.com',
        'www.allaboutdnt.com',
    ],
};

export const graphDataExample2 = {
    nodes: [
        { id: 'https://www.mdn.com/?', group: 1, distanceGroup: 1, explored: true },
        {
            id: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 3,
            explored: true,
        },
        {
            id: 'https://www.trustpilot.com/review/dan.com?',
            group: 3,
            distanceGroup: 4,
            explored: false,
        },
        {
            id: 'https://www.dan.com/trust_and_security?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: true,
        },
        {
            id: 'https://www.mdn.com/cookies?',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: true,
        },
        {
            id: 'https://www.dan.com/disclaimer?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: false,
        },
        {
            id: 'https://www.dan.com/sitemap?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 2,
            explored: true,
        },
        {
            id: 'https://www.mdn.com/?new_locale=nl-nl',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=es-es',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=hi-in',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=de-de',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=fr-fr',
            group: 1,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.mdn.com/?new_locale=zh-cn',
            group: 1,
            distanceGroup: 1,
            explored: true,
        },
        { id: 'https://www.dan.com/?', group: 2, distanceGroup: 1, explored: false },
        {
            id: 'https://www.dan.com/buy_a_domain?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/sell_your_domain?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        { id: 'https://www.dan.pr.co/?', group: 5, distanceGroup: 5, explored: false },
        {
            id: 'https://www.dan.com/trust_and_security?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/help_center?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/transaction_explorer?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/our_story?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/api_partnership_program?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/careers?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/contact?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/users/login?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/search?order_by=views-desc,popular=true,terms=*',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/search?no_hyphens=true,no_numerals=true,no_unicode=true,order_by=views-desc,terms=*,three_digits=true,tld[]=com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/search?order_by=views-desc,premium=true,terms=*,tld[]=com,tld[]=com,tld[]=com,tld[]=com,tld[]=com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/brokerage?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.twitter.com/undeveloped?',
            group: 6,
            distanceGroup: 6,
            explored: false,
        },
        {
            id: 'https://www.domaining.com/feed/dan?',
            group: 7,
            distanceGroup: 7,
            explored: false,
        },
        {
            id: 'https://www.linkedin.com/company/dan-com?',
            group: 8,
            distanceGroup: 8,
            explored: false,
        },
        {
            id: 'https://www.blog.undeveloped.com/?',
            group: 9,
            distanceGroup: 9,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/cookies?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/disclaimer?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/sitemap?',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.supportcenter.godaddy.com/abusereport?',
            group: 10,
            distanceGroup: 10,
            explored: false,
        },
        {
            id: 'https://www.godaddy.com/en-uk/legal/agreements/trademark-copyright-infringement?',
            group: 11,
            distanceGroup: 11,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/terms_of_use?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?archive=2022-12-22',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.allaboutdnt.com/?',
            group: 12,
            distanceGroup: 12,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
        {
            id: 'https://www.dan.com/privacy?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            group: 2,
            distanceGroup: 1,
            explored: false,
        },
    ],
    links: [
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.trustpilot.com/review/dan.com?',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/trust_and_security?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.mdn.com/cookies?',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/disclaimer?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.dan.com/sitemap?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.mdn.com/?new_locale=nl-nl',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.mdn.com/?new_locale=es-es',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.mdn.com/?new_locale=hi-in',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.mdn.com/?new_locale=de-de',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.mdn.com/?new_locale=fr-fr',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?',
            target: 'https://www.mdn.com/?new_locale=zh-cn',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.trustpilot.com/review/dan.com?',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/trust_and_security?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/domain-seller/domain-seller-b81b492c-a8ac-49d0-bc71-a962b82b8513?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.mdn.com/cookies?',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/disclaimer?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.dan.com/sitemap?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.mdn.com/?new_locale=nl-nl',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.mdn.com/?new_locale=es-es',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.mdn.com/?new_locale=hi-in',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.mdn.com/?new_locale=de-de',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.mdn.com/?new_locale=fr-fr',
            strength: 1,
        },
        {
            source: 'https://www.mdn.com/?new_locale=zh-cn',
            target: 'https://www.mdn.com/?new_locale=zh-cn',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/users/login?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/users/login?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/search?order_by=views-desc,popular=true,terms=*',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/search?no_hyphens=true,no_numerals=true,no_unicode=true,order_by=views-desc,terms=*,three_digits=true,tld[]=com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/search?order_by=views-desc,premium=true,terms=*,tld[]=com,tld[]=com,tld[]=com,tld[]=com,tld[]=com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/brokerage?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.twitter.com/undeveloped?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.domaining.com/feed/dan?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.linkedin.com/company/dan-com?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.blog.undeveloped.com/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/cookies?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/disclaimer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sitemap?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/users/login?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/users/login?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/cookies?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/disclaimer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.supportcenter.godaddy.com/abusereport?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.godaddy.com/en-uk/legal/agreements/trademark-copyright-infringement?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/brokerage?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.twitter.com/undeveloped?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.domaining.com/feed/dan?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.linkedin.com/company/dan-com?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.blog.undeveloped.com/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/cookies?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/disclaimer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sitemap?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/terms_of_use?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/users/login?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/users/login?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?archive=2022-12-22',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/cookies?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.allaboutdnt.com/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/buy_a_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sell_your_domain?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/api_partnership_program?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/brokerage?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.pr.co/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/trust_and_security?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/help_center?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/transaction_explorer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/careers?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/our_story?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/contact?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.twitter.com/undeveloped?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.domaining.com/feed/dan?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.linkedin.com/company/dan-com?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.blog.undeveloped.com/?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/cookies?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/terms_of_use?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/disclaimer?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/sitemap?',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?new_locale=nl-nl,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?new_locale=es-es,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?new_locale=hi-in,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?new_locale=de-de,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?new_locale=fr-fr,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
        {
            source: 'https://www.dan.com/privacy?utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            target: 'https://www.dan.com/privacy?new_locale=zh-cn,utm_campaign=Parking,utm_medium=parking,utm_source=.com,utm_term=mdn.com',
            strength: 1,
        },
    ],
};

// function clearGraphData(g) {
//     return JSON.stringify({
//         nodes: g.nodes.map((n) => ({
//             id: n.id,
//             group: n.group,
//             distanceGroup: n.distanceGroup,
//             explored: n.explored,
//         })),
//         links: g.links.map((l) => ({
//             source: l.source.id,
//             target: l.target.id,
//             strength: l.strength,
//         })),
//     });
// }

// console.log(clearGraphData(graphDataExample2));
